### ISSUE TITLE
This web property is not accessible via this address (Cloudflare)

### ISSUE THREAD

**Issue by Kohan12121** [cognetwork-dev/Metallic#10]
when accessing a site protected by Cloudflare I get the following error "This web property is not accessible via this address." If possible make an Cloudflare bypass of some sort so we can get past that error.

Sites: https://www.crunchyroll.com/ and https://chat.openai.com/

**Comment by Prexry** [comment]
It's a proxy, it's blocked. Duh.

**Comment by hiroshil** [comment]
@Nebelung-Dev Reopen issue +1
