### ISSUE TITLE
is metallic down?

### ISSUE THREAD

**Issue by PlumpusMcRich** [cognetwork-dev/Metallic#20]
When I go to metallic it says the site cant be reached, just wondering if its down or what.

**Comment by sheplol** [comment]
for me it just shows a white screen.

**Comment by The-Rock-21** [comment]
![Screenshot 2023-11-13 3 39 04 PM](https://github.com/cognetwork-dev/Metallic/assets/101891804/c08c1d3d-8ec9-4e4a-ac5d-2fbf7a939358)

**Comment by The-Rock-21** [comment]
It's back up now you can close this issue
