### ISSUE TITLE
Were are games at?

### ISSUE THREAD

**Issue by Prozoon700** [cognetwork-dev/Metallic#21]
Hi I was trying to found the Games folder to change, modify and optimize some things but I don't found it.
Are they obtained by other website and linked by an object / iframe?

**Comment by Nebelung-Dev** [comment]
Metallic uses 3kh0's games which can be found [here](https://codeberg.org/3kh0/3kh0-assets)

**Comment by Prozoon700** [comment]
Thanks, but I wheres the link to that, I mean, in the code.
