### ISSUE TITLE
Error: Your browser doesn't support service workers.

### ISSUE THREAD

**Issue by patritha** [cognetwork-dev/Metallic#25]
then connecting to the server over a port forwarded connection this shows up. feel free to ask me if you need more info

**Comment by patritha** [comment]
it does the same thing on chromium

**Comment by Nebelung-Dev** [comment]
can you send a screenshot of the error

**Comment by patritha** [comment]
![image](https://github.com/cognetwork-dev/Metallic/assets/91040285/625af543-013f-499e-aac8-6619d84afd2b)
gives the same dialog box on chromium

**Comment by Nebelung-Dev** [comment]
huh thats really weird. is your browser on the latest version?

**Comment by Nebelung-Dev** [comment]
The problem could be because service workers are not allow on `http://` urls. Maybe you could try turning `devtools.serviceWorkers.testing.enabled` on.

**Comment by patritha** [comment]
how would i get https

**Comment by Nebelung-Dev** [comment]
on firefox with the setting `devtools.serviceWorkers.testing.enabled` i think
