### ISSUE TITLE
I dunno what to do

### ISSUE THREAD

**Issue by AGuywhoquestions** [cognetwork-dev/Metallic#27]
![image](https://github.com/cognetwork-dev/Metallic/assets/160807941/da555849-325f-4b07-9826-50b7e8413216)

**Comment by Cheese-Curd** [comment]
Having the same issue here.

**Comment by Nebelung-Dev** [comment]
It is currently down

**Comment by Cheese-Curd** [comment]
it has been for... what? 3 weeks?

**Comment by Yunlongzzj** [comment]
same

**Comment by Cheese-Curd** [comment]
any idea on when this will be fixed?

**Comment by Nebelung-Dev** [comment]
I'm thinking I'll static host it with an external bare server because I cant really do anything else. Hopefully I can finish up the 2.0 release in the next week and fix it then.
