### ISSUE TITLE
"Client decided to terminate with reason 1" on Koyeb

### ISSUE THREAD

**Issue by neptuneaero27** [cognetwork-dev/Metallic#29]
I can't use it for 30 seconds without that error happening in the Koyeb logs and it stops letting me use Metallic and says that there are no bare clients.

![image](https://github.com/cognetwork-dev/Metallic/assets/118471104/f7a8ca95-b2f3-4919-b12b-ef2bb4063739)
![image](https://github.com/cognetwork-dev/Metallic/assets/118471104/640f223d-a666-4d62-aacd-9f04cc7f16b5)

**Comment by Nebelung-Dev** [comment]
skill jssue
